//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    
    public partial class Employee:IEnumerable<Employee>
    {
        public int Emp_ID { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public Nullable<int> Age { get; set; }
        List<Employee> mylist = new List<Employee>();
        public Employee this[int index]
        {
            get { return mylist[index]; }
            set { mylist.Insert(index, value); }
        }
        public IEnumerator<Employee> GetEnumerator()
        {
            return mylist.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return this.GetEnumerator();
        }
    }
}

